name: Run on merge event

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        if: github.event.pull_request.merged == true
        run: |
          sleep 5
      - name: Wait
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          sleep 5
      - name: Run test
        run: |
          echo hi
