name: Run on merge event

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        if: github.event.pull_request.merged == true
        run: |
          sleep 5
      - name: Run test
        run: |
          echo hi
